defaultAppearance = "light"
colorScheme = "ocean"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true

[author]
  name = "顾宇"

[footer]
  showAppearanceSwitcher = true
  showScrollToTop = true


[homepage]
  layout = "profile" # valid options: page, profile, custom
  showRecent = true

[article]
  showDate = true
  dateFormat = "2 January 2006"
  showAuthor = true
  showBreadcrumbs = true
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showWordCount = true
  showTaxonomies = true
  showTableOfContents = true

[list]
  showTableOfContents = true
  showBreadcrumbs = true

